### ISSUE TITLE
Launcher entry not added in Lab

### ISSUE THREAD

**Issue by mjuric** [yuvipanda/jupyter-desktop-server#18]
When I install this package I do see a new entry in the classic notebook's 'New' menu, but there's no corresponding launcher entry when I switch to Lab:

![image](https://user-images.githubusercontent.com/620059/85944973-62a69400-b8ef-11ea-9d22-a3a1e9347101.png)

Is this a bug, or I'm looking at the wrong place? Adding an explicit:
```
        'launcher_entry': {
            'title': 'Desktop',
            'icon_path': os.path.join(HERE, 'share/icons/desktop.svg')
        }
```
to the `setup_desktop` routine didn't help.

For reference, this is the Dockerfile to reproduce:
```
FROM jupyter/scipy-notebook:latest

USER root
RUN apt-get -y update && apt-get install -y dbus-x11 xfce4 xfce4-panel xfce4-session xfce4-settings xorg xubuntu-icon-theme
RUN apt-get -y update && apt-get install -y dbus-x11 firefox

USER $NB_USER
RUN conda install -c manics websockify
RUN pip install jupyter-desktop-server
```

**Comment by yuvipanda** [comment]
You need the [jupyter-server-proxy](https://github.com/jupyterhub/jupyter-server-proxy/#jupyterlab-extension) labextension for this. The classic notebook extension is installed by default, unfortunately we can't do that for lab.

**Comment by mjuric** [comment]
`jupyter labextension install @jupyterlab/server-proxy` did it, thanks!

**Comment by mjuric** [comment]
@yuvipanda One more question -- I see an oddly rendered character in the parentheses next to the icon:

![image](https://user-images.githubusercontent.com/620059/85945794-e911a480-b8f4-11ea-8d3c-c108bdc34f02.png)

Is that a known bug (or am I doing something wrong)?

(ignore the fact it's a VSCode icon -- it's just a temporary stand-in while I'm playing with this).

**Comment by yuvipanda** [comment]
@mjuric It was fixed in https://github.com/jupyterhub/jupyter-server-proxy/pull/201 but not released yet. @consideratio do you have rights to make a jupyterlab extension release?

**Comment by consideRatio** [comment]
@yuvipanda jupyterlab extension v2.1.1 released!

**Comment by yuvipanda** [comment]
@consideRatio awesome, thank you :)
