### ISSUE TITLE
Graphics performances

### ISSUE THREAD

**Issue by djangoliv** [yuvipanda/jupyter-desktop-server#24]
I recently swtich from https://gitlab.com/logilab/nbnovnc to jupyter-desktop-server.
The configuration and the configuration is really easier, thanks for this extension.
But with nbnovnc I could run glxgears and blender. On the other hand with jupyter-desktop-server, I cannot.
With glxgears I get  `Error: couldn't get an RGB, Double-buffered visual.`

I added a Dockerfile on nbnovnc for you to try.

Regards

**Comment by manics** [comment]
A few months ago @yuvipanda mentioned TurboVNC as having better OpenGL support. I've got an experimental branch here you could try:
https://github.com/manics/jupyter-omeroanalysis-desktop/tree/turbovnc (ignore the launch from binder button as it's not pointing to the branch)

**Comment by djangoliv** [comment]
@manics Thanks, it works fine with turbovnc. 
I look forward to your MR :)

**Comment by djangoliv** [comment]
@manics I think you should make a PR with your branch "turbovnc". it really works better with turbovnc!

Regards
