### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by djangoliv** [yuvipanda/jupyter-desktop-server#25]
After a few minutes of inactivity, the screen goes black and it is impossible to reactivate it.

Regards

**Comment by alexhersh** [comment]
I am also experiencing this issue. I am running on a kubernetes cluster with GPUs attached to user pods. I also switched to TurboVNC as my VNC provider (as opposed to TigerVNC). Behavior is as described above.

**Comment by RaisoLiu** [comment]
I have a solution.
Use this command 
`ps -ef | grep -E 'screen|lock'`
check process "light-locker" status.

It makes screen black, so kill it.
`kill -9 $(pgrep -f light-locker)`

**Comment by djangoliv** [comment]
Thanks @raiso777. I removing light-locker resolved my problem.
