### ISSUE TITLE
Desktop "frozen" after left idle

### ISSUE THREAD

**Issue by cslocum** [yuvipanda/jupyter-desktop-server#35]
Hello!  I'm running into a problem where the desktop "freezes" when I navigate away from the tab for a while (10-15 mins?).  Once I go back to that tab, neither clicking around or refreshing will bring it back to a working state.  Neither will closing that tab and restarting the desktop from the Lab launcher.

Stopping and restarting the server will restore working desktop functionality.  Here's a (probably unhelpful) screenshot of what this failure mode looks like:

![image](https://user-images.githubusercontent.com/6738995/113161138-1b498d00-920c-11eb-8a67-e5b4034245ba.png)

I'm not seeing any networking errors in the browser console, and system resources are not maxed out anywhere.

I'm sorry I don't have any more concrete information to add here.  I don't see any other reports of this issue, so I'm wondering if I've just set things up wrong, or if anything obvious occurs to someone.

**Comment by cslocum** [comment]
Come to think of it, I'm not sure this is the right place to have posted this issue.

**Comment by djangoliv** [comment]
IMHO: same as issue #25

**Comment by cslocum** [comment]
Ah, thanks for linking me to that!

**Comment by cslocum** [comment]
Thank you @djangoliv!  This solved my problem.
